# Generated by Django 6.0.6 on 2026-06-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_examsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprogress',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
